const descriptions = [
  "Spacious and comfortable with modern furniture.",
  "Perfect for couples seeking relaxation.",
  "Bright room with natural sunlight and cozy design.",
  "Ideal for families looking for a calm stay.",
  "Luxury experience with elegant décor.",
  "Enjoy the peaceful garden view.",
  "Wake up to the sound of the sea.",
  "Simple, clean, and affordable option.",
  "Modern style with traditional comfort.",
  "Designed for ultimate relaxation.",
  "Perfect getaway for short stays.",
  "Spacious bathroom with premium amenities.",
  "Balcony overlooking the beautiful city.",
  "Enjoy a warm and inviting atmosphere.",
  "Elegant room with soft lighting.",
  "Best choice for honeymooners.",
  "Practical design for business travelers.",
  "Comfortable beds with fresh linens.",
  "Large windows with great views.",
  "Private and peaceful atmosphere.",
  "Minimalist design with all essentials.",
  "Relaxing ambiance with modern touch.",
  "Ideal spot for enjoying sunsets.",
  "Premium comfort at an affordable price.",
  "Stylish décor with a homely feel.",
  "Spacious suite for families.",
  "Romantic vibe for couples.",
  "Fully furnished with attention to detail.",
  "Quiet environment for full relaxation.",
  "Simple design with functional comfort.",
  "High-quality service and amenities.",
  "Unique blend of style and comfort.",
  "Enjoy an unforgettable stay.",
  "Perfect balance of luxury and simplicity.",
  "Private balcony with stunning views.",
  "Relax and recharge in style.",
  "Modern furniture with a cozy touch.",
  "Spacious enough for friends and family.",
  "Warm colors and welcoming design.",
  "Sea breeze right from your window.",
  "Peaceful and quiet for deep rest.",
  "Roomy suite with stylish interior.",
  "Affordable luxury experience.",
  "Fresh, clean, and comfortable stay.",
  "Beautiful views from every angle.",
  "Relaxed atmosphere with cozy vibes.",
  "Perfect for both work and leisure.",
  "Designed for maximum comfort.",
  "Spacious interiors with soft tones.",
  "Wake up refreshed every morning.",
  "Enjoy high-end hotel comfort.",
  "City lights right outside your window.",
  "Beautifully decorated and well-lit.",
  "Garden view with peaceful vibes.",
  "Feel at home with extra space.",
  "Premium bedding for deep sleep.",
  "Luxury bathroom with modern design.",
  "Cozy environment for perfect relaxation.",
  "Ideal for long vacations.",
  "Classic design with modern facilities.",
  "Experience comfort like never before.",
  "Relax in a stylish and calm setting.",
  "Perfect choice for family trips.",
  "Romantic sea-view experience.",
  "Bright and airy with elegant touch.",
  "Fully equipped for your comfort.",
  "Unwind in a peaceful retreat.",
  "Enjoy modern living by the sea.",
  "City-view room with urban charm.",
  "Warm ambiance with luxury comfort.",
  "Spacious double room for couples.",
  "Fresh design with relaxing vibes.",
  "High-class service with cozy feel.",
  "Private suite with elegant design.",
  "Enjoy natural light all day long.",
  "A comfortable place to recharge.",
  "Relax and enjoy premium amenities.",
  "Luxury suite with sea views.",
  "Cozy décor with homely comfort.",
  "Quiet and private for total peace.",
  "Garden-view for nature lovers.",
  "Simple yet elegant design.",
  "Bright interiors with soft décor.",
  "Stylish suite with modern luxury.",
  "Affordable comfort by the sea.",
  "Enjoy a relaxing evening view.",
  "Spacious and clean double room.",
  "Perfect balance of beauty and comfort.",
  "Modern comfort with classic touch.",
  "Peaceful stay with natural beauty.",
  "Family-friendly and cozy.",
  "Premium room with stunning views.",
  "Unwind in total privacy.",
  "Luxury bedding with top comfort.",
  "Balcony with breathtaking scenery.",
  "Classic comfort meets modern design.",
  "Perfect for vacations and weekends.",
  "Spacious interiors with cozy vibe.",
  "Bright room with a peaceful feel.",
  "Enjoy sea sunsets from your bed.",
  "Charming décor with relaxing tones."
];

module.exports = descriptions;